set(visrtx_options)
if (UNIX AND NOT APPLE)
  list(APPEND visrtx_options
    -DCMAKE_INSTALL_RPATH:STRING=<INSTALL_DIR>/lib)
endif ()

superbuild_add_project(visrtx
  DEPENDS anari nvidiamdl nvidiaoptix
  LICENSE_FILES
    LICENSE
  SPDX_LICENSE_IDENTIFIER
    BSD-3-Clause
  SPDX_COPYRIGHT_TEXT
    "Copyright (c) 2019, NVIDIA CORPORATION"
  CMAKE_ARGS
    -DBUILD_SHARED_LIBS:BOOL=${BUILD_SHARED_LIBS}
    -DCMAKE_MACOSX_RPATH:BOOL=FALSE
    -DCMAKE_INSTALL_NAME_DIR:PATH=<INSTALL_DIR>/lib
    -DCMAKE_INSTALL_LIBDIR:STRING=lib
    -DVISRTX_BUILD_EXAMPLES:BOOL=OFF
    -DVISRTX_BUILD_INTERACTIVE_EXAMPLE:BOOL=OFF
    -DVISRTX_ENABLE_MDL_SUPPORT:BOOL=ON
    ${visrtx_options})
